[package]
name = "wasm-module"
version = "0.2.0"
authors = ["Kai Page <kaibug@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
compiler = { path = "../compiler" }

wasm-bindgen = "0.2.55"