[package]
name = "compiler"
version = "0.2.0"
authors = ["Kai Page <kaibug@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
leb128 = "0.2.4"
#log = "0.4.8"
